{
 "title": "Chainlink Monitor",
 "time": { "from": "now-14d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Head",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "head_tracker_current_head{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "Head Tracker Callback Execution Time",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "head_tracker_callback_execution_duration{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "Eth Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "eth_balance{job=~\"chainlink_p.*\"}",
     "legendFormat": "{{account}}"
    }
   ]
  },
  {
   "title": "Heads dropped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "targets": [
    {
     "expr": "head_tracker_num_heads_dropped{job=~\"chainlink_p.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head Tracker Heads in Queue",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "head_tracker_heads_in_queue{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "expr": "run_queue_queue_size{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "New heads per minute",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "rate(head_tracker_heads_received{job=~\"chainlink_p.*\"}[1m])*60"
    }
   ]
  },
  {
   "title": "Job Subscriptions",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "expr": "job_subscriber_subscriptions{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "Eth Balance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "eth_balance{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "Gas Price Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gas_updater_set_gas_price{job=~\"chainlink_p.*\",block_num=\"\"}/1000000000",
     "legendFormat": "actual"
    }
   ]
  },
  {
   "title": "Gas Price Percentiles",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gas_updater_all_gas_percetiles{percentile!=\"100%\",job=~\"chainlink_p.*\"}/1000000000",
     "legendFormat": "{{percentile}}"
    }
   ]
  },
  {
   "title": "Errored Jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(adapter_perform_complete_total{status=\"errored\", job=~\"chainlink_p.*\"}[1d])",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "New heads per minute",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(head_tracker_heads_received{job=~\"chainlink_p.*\"}[1m])*60"
    }
   ]
  },
  {
   "title": "Uncled Jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(run_status_update_total{from_status=\"pending_outgoing_confirmations\", status=\"errored\",job=~\"chainlink_p.*\"}[1d])\n",
     "legendFormat": "{{job_spec_id}}"
    }
   ]
  },
  {
   "title": "Errored Tasks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(adapter_perform_complete_total{status=\"errored\",job=~\"chainlink_p.*\"}[1d]) ",
     "legendFormat": "{{task_type}}"
    }
   ]
  },
  {
   "title": "Number of Jobs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (increase(adapter_perform_complete_total{status=\"completed\", task_type=\"ethtx\",job=~\"chainlink_p.*\"}[1d]))\n"
    }
   ]
  },
  {
   "title": "Current Head increase",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(head_tracker_current_head{job=~\"chainlink_p.*\"}[1m])*60",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Head Tracker Heads in Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "head_tracker_heads_in_queue{job=~\"chainlink_p.*\"}"
    }
   ]
  },
  {
   "title": "Number of Gas Bumps",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "tx_manager_num_gas_bumps{job=~\"chainlink_p.*\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "All Job Runs",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(adapter_perform_complete_total{status=\"completed\",task_type=\"ethtx\",job=~\"chainlink_p.*\"}[1d])\n",
     "legendFormat": "{{job_spec_id}}"
    }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 10, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txpool_pending{job=~\"ethereum.*\"}",
     "legendFormat": "executable {{job}}"
    },
    {
     "expr": "txpool_queued{job=~\"ethereum.*\"}",
     "legendFormat": "gapped {{job}}"
    },
    {
     "expr": "txpool_local{job=~\"ethereum.*\"}",
     "legendFormat": "local {{job}}"
    }
   ]
  }
 ]
}